@startwbs
'https://plantuml.com/wbs-diagram
<style>
wbsDiagram{
FontSize: 45
}
</style>
* **ENG1 Assessment 2**
**[#LightBlue] Website
*** Update the files
*** Add new deliverables
**[#LightGreen] Implementation
*** Bug fixes and minor changes
*** Break up <i>GameScreen</i> class
*** Add new map
*** Add new locations
*** Display stats
*** Add scoring
*** Add leaderboard
**[#LightSalmon] Testing
*** Adding testing
*** Writing tests for old code
*** Writing tests for new code as it is written
*** Write up
**[#LightGoldenRodYellow] Continuous Integration
*** Implementing continuous integration
*** Write up
**[#Tomato] User evaluation
*** Evaluation meetings
*** Write up
*** Action
**[#LightCyan] Change Report
*** Implementation changes
*** Update Deliverables
**** Plan1
**** Req1
**** Arch1
**** Risk1
**** Imp1


@endwbs