@startwbs
'https://plantuml.com/wbs-diagram
<style>
wbsDiagram{
FontSize: 45
}
</style>
* **ENG1 Assessment 2**
**[#LightBlue] Website
*** Set up the\n\
website clone
*** Fix gantt typo
*** Edit titles\n\
to differentiate\n\
from previous\n\
group
*** Add new\n\
deliverables
**[#LightGreen] Implementation
*** Bug fixes and\n\
minor changes
*** Break up\n\
<i>GameScreen</i>\n\
class
*** Add new map
*** Add new locations
*** Display stats
*** Add scoring
*** Add leaderboard
*** Produce final JAR
**[#LightSalmon] Testing
*** Adding testing
*** Writing tests for\n\
old code
*** Writing tests for\n\
new code as it\n\
is written
*** Write up
**[#LightGoldenRodYellow] Continuous Integration
*** Implementing\n\
continuous\n\
integration
*** Write up
**[#Tomato] User evaluation
*** Evaluation\n\
meetings
*** Write up
*** Action
**[#LightCyan] Change Report
*** Introduction
*** Update\n\
Deliverables
**** Plan1 -> Plan2
**** Req1 -> Req2
**** Arch1 -> Arch2
**** Risk1 -> Risk2


@endwbs