name: Java CI with Gradle
on:
  # Trigger the workflow on push or pull request to main branch
  push:
    branches: [ main ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ main ]
jobs:
  # Build the gradle project
  build:
    runs-on: ubuntu-latest
    # Permission to access the repository
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle and run tests with JaCoCo coverage and Checkstyle
        uses: gradle/actions/setup-gradle@v3
        with:
         arguments: build jacocoTestReport

      - name: Upload JaCoCo coverage report as a workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: tests/build/reports/jacoco/test/html/

      - name: Upload library JAR
        uses: actions/upload-artifact@v4
        with:
          name: desktop-1.0.jar
          path: desktop/build/libs/desktop-1.0.jar

      - name: Upload Core Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: core-checkstyle-report
          path: core/build/reports/checkstyle/main.html

      - name: Upload Desktop Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: desktop-checkstyle-report
          path: desktop/build/reports/checkstyle/main.html

      - name: Upload Test Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: tests-checkstyle-report
          path: tests/build/reports/checkstyle/main.html

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download the Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: desktop-1.0.jar

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: desktop-1.0.jar
