name: Java CI with Gradle
on:
  # Trigger the workflow on push or pull request to main branch
  push:
    branches: [ main, KAN-8-Implement-testing-in-CI ]
  pull_request:
    branches: [ main ]
jobs:
  # Build the gradle project
  build:
    runs-on: ubuntu-11.04
    # Permission to access the repository
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3