name: Java CI with Gradle
on:
  # Trigger the workflow on push or pull request to main branch
  push:
    branches: [ main, KAN-8-Implement-testing-in-CI ]
  pull_request:
    branches: [ main ]
jobs:
  # Build the gradle project
  build:
    runs-on: ubuntu-latest
    # Permission to access the repository
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build jacocoTestReport
      - name: Upload JaCoCo coverage report as a workflow artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: jacoco-report
          path: tests/build/reports/jacoco/test/html/